/*
  Warnings:

  - Added the required column `DESCRICAO` to the `VEICULO` table without a default value. This is not possible if the table is not empty.

*/
-- RedefineTables
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_VEICULO" (
    "ID" TEXT NOT NULL PRIMARY KEY,
    "DESCRICAO" TEXT NOT NULL,
    "TIPO_CODIGO" INTEGER NOT NULL,
    "MOTORISTA_CODIGO" INTEGER NOT NULL,
    "APARELHO_ID" TEXT NOT NULL,
    CONSTRAINT "VEICULO_TIPO_CODIGO_fkey" FOREIGN KEY ("TIPO_CODIGO") REFERENCES "TIPO_VEICULO" ("CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "VEICULO_MOTORISTA_CODIGO_fkey" FOREIGN KEY ("MOTORISTA_CODIGO") REFERENCES "MOTORISTA" ("CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "VEICULO_APARELHO_ID_fkey" FOREIGN KEY ("APARELHO_ID") REFERENCES "APARELHO" ("ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_VEICULO" ("APARELHO_ID", "ID", "MOTORISTA_CODIGO", "TIPO_CODIGO") SELECT "APARELHO_ID", "ID", "MOTORISTA_CODIGO", "TIPO_CODIGO" FROM "VEICULO";
DROP TABLE "VEICULO";
ALTER TABLE "new_VEICULO" RENAME TO "VEICULO";
PRAGMA foreign_key_check;
PRAGMA foreign_keys=ON;
