-- RedefineTables
PRAGMA foreign_keys=OFF;
CREATE TABLE "new_LOCALIZACAO" (
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "LATITUDE" REAL NOT NULL,
    "LONGITUDE" REAL NOT NULL,
    "ID_APARELHO" INTEGER NOT NULL,
    "DATAHORA" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "LOCALIZACAO_ID_APARELHO_fkey" FOREIGN KEY ("ID_APARELHO") REFERENCES "APARELHO" ("ID") ON DELETE RESTRICT ON UPDATE CASCADE
);
INSERT INTO "new_LOCALIZACAO" ("DATAHORA", "ID", "ID_APARELHO", "LATITUDE", "LONGITUDE") SELECT "DATAHORA", "ID", "ID_APARELHO", "LATITUDE", "LONGITUDE" FROM "LOCALIZACAO";
DROP TABLE "LOCALIZACAO";
ALTER TABLE "new_LOCALIZACAO" RENAME TO "LOCALIZACAO";
PRAGMA foreign_key_check;
PRAGMA foreign_keys=ON;
