-- CreateTable
CREATE TABLE "TIPO_VEICULO" (
    "CODIGO" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "DESCRICAO" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "MOTORISTA" (
    "CODIGO" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "NOME" TEXT NOT NULL
);

-- CreateTable
CREATE TABLE "VEICULO" (
    "ID" TEXT NOT NULL PRIMARY KEY,
    "TIPO_CODIGO" INTEGER NOT NULL,
    "MOTORISTA_CODIGO" INTEGER NOT NULL,
    CONSTRAINT "VEICULO_MOTORISTA_CODIGO_fkey" FOREIGN KEY ("MOTORISTA_CODIGO") REFERENCES "MOTORISTA" ("CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "VEICULO_TIPO_CODIGO_fkey" FOREIGN KEY ("TIPO_CODIGO") REFERENCES "TIPO_VEICULO" ("CODIGO") ON DELETE RESTRICT ON UPDATE CASCADE
);
