-- CreateTable
CREATE TABLE "LOCALIZACAO" (
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "Latitude" REAL NOT NULL,
    "Longitude" REAL NOT NULL,
    "ID_APARELHO" INTEGER NOT NULL,
    "DATAHORA" DATETIME NOT NULL,
    CONSTRAINT "LOCALIZACAO_ID_APARELHO_fkey" FOREIGN KEY ("ID_APARELHO") REFERENCES "APARELHO" ("ID") ON DELETE RESTRICT ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "APARELHO" (
    "ID" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    "DESCRICAO" TEXT NOT NULL
);
